### PR TITLE
Made it compatible with the changed Position API of jQuery UI 1.9 .

### PR DESCRIPTION
**Pull request by lephyrius**
http://blog.jqueryui.com/2010/12/position-api-redesign/
This is the changed Position API for jQuery UI 1.9 .

### CODE REVIEW

**Comment by fnagel** [comment]
Sorry about the long waiting time, but I had an surgery and was not able to work on the selectmenu widget the last few weeks.
This will be very useful when updating to the latest jQuery / UI version. Thanks for your contribution!

**Comment by yojeek** [comment]
it works, please merge!..

**Comment by fnagel** [comment]
This will be integrated when 1.9 is officially released.

Please take a look at the new built from scratch version of Selectmenu which uses 1.9 and UI menu: #140

**Comment by fnagel** [comment]
Did somebody test the latest version?

**Comment by fnagel** [comment]
jQuery 1.9 will not be integrated in this version of Selectmenu. Use the new, built from scratch version instead: see #140

**Comment by fnagel** [comment]
Reopened as the new Selectmenu version will be released with jQuery UI 1.10.

**Comment by fnagel** [comment]
I am not able to reopen this pull request. I will test this when working on jQuery UI 1.9 compatibility. Please send a new pull request if possible. Sorry for the circumstances.

**Comment by fnagel** [comment]
I've updated to jQuery 1.9.2, please test and give feedback!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Pull request closed without merging**
