### PR TITLE
Solve problem when creating widget with indirectly hidden SELECT

### PR DESCRIPTION
**Pull request by abssoft**
Solve problem when creating widget with indirectly hidden SELECT (in particular inside UITab)

### CODE REVIEW

**Comment by fnagel** [comment]
Thanks for your contribution. Would you please gve a short description and a demo fiddle (see #61) which explains the issue.

**Comment by abssoft** [comment]
I apologize that I hurry to commit. That problem should be investigated out more. )

**Comment by fnagel** [comment]
I apologize and hope you would deliver a demo as I have no idea what exactly you try to fix here.

**Comment by alexking** [comment]
I think he may have been trying to fix this bug - if you initialize a selectmenu on a select in a hidden container, when you first  click the drop down it scrolls to the top of the page. You can see that in this fiddle http://jsfiddle.net/qAsEH/

This commit didn't seem to fix the problem for me though, so perhaps this needs to be a new issue.

**Comment by fnagel** [comment]
Ahh I see. This seems to be related to this issue: #147
Im currently very busy implementing a new version from scratch (see here for more info: #140), but I will take a look asap. Please be patient.

**Comment by fnagel** [comment]
@alexking
Please open an new issue for this issue. See #61

@ArtemBreslavskiy 
Please try jquery peek, see the wiki https://github.com/fnagel/jquery-ui/wiki/Selectmenu
Search for "Using Selectmenu within Tabs or Lightboxes"

**Comment by fnagel** [comment]
This problem should be solved by issue #147

**Comment by fnagel** [comment]
Should be solved in v1.2. Closed as no feedback was given. Please reopen if needed.

**Pull request closed without merging**
