### PR TITLE
MERGE 1.8.17 from jquery-ui

### PR DESCRIPTION
**Pull request by ainformatico**

### CODE REVIEW

**Comment by fnagel** [comment]
Did you test this in al major browser? Why dont you update jQuery UI?

**Comment by ainformatico** [comment]
Tested with IE6, FF10 and Chrome16.
I'm using selectmenu along with almost all the jQuery UI components, so I think that it's a good idea to keep this project in sync with the main jQuery UI for deploy reasons and see selectmenu integration with all the new updates from the jQuery UI team.
It's too hard to maintain two different repos to generate one js file.

**Comment by fnagel** [comment]
Ahhh ok, I will test and merge this together with #213 and #214. Both would need a helping hand and testing!

Please be patient this project is a one man show and Im about to move to another city. Perhaps you would like to take a look at the new, built from scratch version? See #140

**Comment by fnagel** [comment]
1.7.18 us out. I will update my branch soon. 

Pull request outdated.

**Comment by ainformatico** [comment]
I'm also very busy these days, but I'm trying to keep this up to date.

**Comment by fnagel** [comment]
Are you sure this will work? Some poeple reported bugs when using jQuery 1.7.1, see https://github.com/fnagel/jquery-ui/issues?labels=Update-jQuery-version&state=open
Afaics you did no changes to selectmenu itself. Did you test this?

**Comment by fnagel** [comment]
Ahhh this is outdated. Sorry...

**Pull request closed without merging**
