### PR TITLE
destroy widget with no associated label

### PR DESCRIPTION
**Pull request by stevemayhew**
Felix,
Thanks for the great work on this component.  Here's the markup (basically) that generates the error:
  <form ...>
        <select class="sortby_control" title="Sort the files and folders list by...">
           <option selected value="f_name">Name</option>
        ...
        </select>
We are using qTip2 and there is a qTip on the <select> (this works!).  qTip2 replace the attr() function just for title (fetches oldtitle instead), but that is not the cause of the error here.

Best,
Steve

### CODE REVIEW

**Comment by stevemayhew** [comment]
Ignore the revert's my bad.  fff8147 is the change you want.

**Comment by fnagel** [comment]
There is no meaningful title, no usable error description, no demo, no code example -- just a few commits in a pull request. 

So what? Should I close it or will you try again to make a usable bug report (see #61)? Sorry for the harsh words but Im receiving more and more requests without any usable info and its driving me mad!

**Comment by stevemayhew** [comment]
Feilx,
So sorry.  The GitHub folks could use some help with usability!  It's not clear to me what all is visible to you, I made pretty extensive comments on the commit in our repository.

I can make a code sample that demonstrates the error.  But basically if you do not have a <label> and id on the <select> element the error will occur.

This code in the destroy() method for selectmenu:
        // unbind click on label, reset its for attr
        $( 'label[for=' + this.newelement.attr('id') + ']' )
            .attr( 'for', this.element.attr( 'id' ) )
            .unbind( '.selectmenu' );

The second function call in the chain, attr(), returns 'undefined' if there is no ID attribute on the initial select element and no "<label for=..." element.

So I get that the code is trying to restore the 'for' attribute of the <label> tag, however if there is no such tag it will error out.

I can make a short code sample for you that shows the problem.  It will take me a couple days to get to it.

PS did you see this text (looks like the unescaped HTML content was ...'d by GitHub):

---

Felix,
Thanks for the great work on this component. Here's the markup (basically) that generates the error:

Name
...

We are using qTip2 and there is a qTip on the (this works!). qTip2 replace the attr() function just for title (fetches oldtitle instead), but that is not the cause of the error here.
Best,
Steve

---

**Comment by fnagel** [comment]
Are you sure youre using the latest version? The above mentioned code snippet is not in selectmenu anymore. Your problem seems to be fixed in #164

ps: try typing "m" when NOT in a textarea!

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by stevemayhew** [comment]
Felix,
Sorry this has taken so long.  I'm in the middle of a release.  Here's a gist:
https://gist.github.com/1529284

Simple click 'create' to create the selectmenu and destroy to destroy it, you'll see the error in the console on the destroy.
Sorry it's ugly, I did not thing with the CSS :-)

That shows the problem, using the version of selectmenu on your demo page.  Feel free to try it against the latest, It still does not work. My fix in this pull request fixes the issue.

**Comment by fnagel** [comment]
As I already mentioned the version (http://jquery-ui.googlecode.com/svn/branches/labs/selectmenu/ui.selectmenu.js) you are using is outdated. Please grab the latest code from this GitHub repo.

Heres a prepared example with the latest code available: #61

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by stevemayhew** [comment]
Felix,
Thanks looks like the latest code has fixed the issue, as destroy is pretty different.  Please ignore my pull.

I'll delete my fork and move to the latest code.

Sorry for the false alarm.
-s

**Comment by fnagel** [comment]
No problem. Im glad we solved this.

**Pull request closed without merging**
