### PR TITLE
Makes the selectmenu scrollable on iOS

### PR DESCRIPTION
**Pull request by chadedrupt**
Simply added -webkit-overflow-scrolling: touch; to the select menu

### CODE REVIEW

**Comment by fnagel** [comment]
I need to test this, seems like a nice little enhancement. Thanks for your contribution!

**Comment by fnagel** [comment]
Ive tested the default demo (second selectmenu) without problems on iPad 1. Im able to scroll but no scrollbars are shown. No scrollbars are a typical problem of iCrab which needs a general (global) solution.

Can you give me more precice information or a demo?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by zuormo** [comment]
I've Tried with an iPhone 4 up to date and seems to work. May be present a small issue because when you click first time the selectmenu (dropdown) the menu appear and then disappear after few milliseconds. But then if you click again it start to work properly.
As you said the component scroll but it doesn't show any scrollbar. Hope this will be usefull. Bye

**Comment by fnagel** [comment]
So you agree, the above mentioned patch is no needed?

**Comment by zuormo** [comment]
Well the selectmenu is scrolling so, I agree that the scrolling script does not need a fix. But just to be correct, If a user don't see any scrollbar, usually think that he have nothing to scroll. So if a graphical rendering of a scrollbar could be implemented, it would make the component more efficient... This is my point of view... It's not a rule...

**Comment by fnagel** [comment]
I agree a scrollbar would be nice but there a whole complex plugins to
handle scrollbars in iOS. This is a general problem for all overflow areas
and scrollbar handling is not part of Selectmenu's core functionality. Im
not willing to fix every iCrap browser issue.

**Comment by chadedrupt** [comment]
Sorry for the lack of feedback, I decided to not load the selectmenu on iOS devices, there default iOS select is bettter suited to the task.

Chad

**Comment by fnagel** [comment]
So, what exactly does your above patch change? How does it help when using Selectmenu in iOS?

That would be best solution in my opinion, too! Would you mind give some feedback how you did this? There is a issue about this, see and comment here: #73

**Comment by chadedrupt** [comment]
> > So, what exactly does your above patch change? How does it help when using Selectmenu in iOS?

It enables scrolling with inertia in iOS 5 and greater

**Comment by fnagel** [comment]
So I need at least a iPhone 4s or a iPad 3, right? 
Without the CSS adjustment Selectmenu wont work on that these devices?

**Comment by chadedrupt** [comment]
No, sorry, Wasn't being clear. It will work, but it works much better in iOS5 with this CSS adjustment. It allows you to flick and the menu will continue to scroll based on how quickly you flicked.

iOS 5 is for iPhone 3gs and newer, all iPads and iPod touch 3rd Gen and newer

**Comment by fnagel** [comment]
Thanks for your feedback! I will include this in my next dev cylce.

**Pull request merged**
