### PR TITLE
sequencial typeahead

### PR DESCRIPTION
**Pull request by spacedevin**
added sequencial typeahead as the default option and left repeated typeahead as an option.
added the typeahead attribute for options.
added back typeahead for open menus. 
resolved https://github.com/fnagel/jquery-ui/issues/#issue/56

### CODE REVIEW

**Comment by fnagel** [comment]
Text from issue56: 

The default functionality on a selectmenu element in OSX is to find "better" options if more than one key is pressed after one another. Currently ui.selectmenu is cycling through all the available options based on a single character.

**Comment by fnagel** [comment]
Implemented but not yet committed. Waiting for reference for typeahead attribute.

See https://github.com/arzynik/jquery-ui/commit/5df784f72b55b62e4b29c8a78237cb996390670c#commitcomment-256885

Documented in Wiki, waiting for reference to add typeahead attribute.

**Comment by revsystems** [comment]
I noticed that typeahead doesn't work when the selectmenu is opened with the mouse. The default `select` element allows this. Should it be supported?

**Comment by fnagel** [comment]
Yes, it should be supported. Did you test arzynik's branch? 
I committed the changes, please give feedback!

**Comment by chewi** [comment]
I don't need this feature so I don't have time to spend on the details but the current sequential typeAhead code (1e623b94b0dfcf116b6b) seems to cause an error in IE8 - 'undefined' is null or not an object.

**Comment by fnagel** [comment]
I will test this asap. Thanks for your contribution.

**Comment by fnagel** [comment]
@chewi 
Your right there is a js error in IE 8-7 (6 untested). I temporally fixed this by disabling sequential typeahead for IE.

@arzynik
Could you do some investigation? Im pretty busy atm and you're already into this typeahead thing :-)

Please check your commit as I commented a line which needs some attention.

**Comment by fnagel** [comment]
Note: I wrote @arzynik a message if he is able to fix this issue as the functionality was created by him.

**Comment by bergerb** [comment]
line 465 
el._prevChar = undefined; 
to 
self._prevChar = undefined;

Fixes the IE8 js error and works in Firefox 4.0.1 / IE8

Just thought I would share.

**Comment by fnagel** [comment]
Sorry about the long waiting time, but I had an surgery and was not able to work on the selectmenu widget the last few weeks. I will take a look asap, please be patient!

**Comment by fnagel** [comment]
@bergerb
Thanks for your contribution! Your fix seems to work pretty nice.

**Comment by bergerb** [comment]
I rewrote a bunch of code within the sequential typeahead.  I will post sometime.  :)

**Comment by fnagel** [comment]
@bergerb
@all

Please take a look at this issue: https://github.com/fnagel/jquery-ui/issues/144
Typeahead wont work when typing the same char agaun.

**Comment by fnagel** [comment]
Would you mind take a look at this pull request which is about typeAhead, too? See #181

**Pull request closed without merging**
