### PR TITLE
jquery.ui.position.js

### PR DESCRIPTION
**Pull request by aetchegoyen**
Fixed line 102: On firefox 3.6.12, using jQuery 1.4.4, and jQuery UI 1.8.6 when a window was resized an error "setting a property that has only a getter", this was because the basePosition var was setted like basePosition = target.offset(), that seems to be read only in jquery 1.4.4, but now, setting it like this: basePosition = { top:target.offset().top, left: target.offset().left}; works like a charm, as it creates a new modificable object.

### CODE REVIEW

**Comment by fnagel** [comment]
I will not fix any third party or better official plugins of jQuery UI in this branch. 

Please take a look at this issue as it seems this could be your problem and was solved by crob611:
https://github.com/fnagel/jquery-ui/issues#issue/44 

Does his bugfix work for you?

**Comment by cburgdorf** [comment]
Mmh, unfortunatly I must admit that I'm still getting the exact same error message. Triggered by a call of _refreshPosition. I tried it with jquery-ui 1.8.5 and 1.8.7. However I'm only getting it when application starts which causes a window resize event to happen as well. However, I already have this fix: https://github.com/fnagel/jquery-ui/issues#issue/44

Issue 44 fixed several of these errors but one at application startup still remains.

**Comment by aetchegoyen** [comment]
Hi cburdorf, try my fix and tell me!
Good luck!

**Comment by fnagel** [comment]
@aetchegoyen
Did you search the jQuery Bugtracker for this problem?

How can I reproduce the problem? Does this problem exists when using the current version of my branch?

**Comment by fnagel** [comment]
A gentle reminder. please give feedback so this issue could be solved.

**Comment by thg2k** [comment]
This was fixed upstream, it's actually a JQuery issue, not a JQueryUI issue. See:
https://github.com/jquery/jquery/commit/c1d719b580ea78c33961113030d7fa25bcc98e6f

you can close this.

**Comment by fnagel** [comment]
Nice, thanks for your feedback!

**Pull request closed without merging**
