### PR TITLE
Plugins which wrap the selectmenu content make it non-clickable

### PR DESCRIPTION
**Pull request by jakob-stoeck**
e.g. when using the jScrollPane plugin for a custom scrollbar inside the menu dropdown like this:

``` js
$('select').selectmenu().next('span').find('a.ui-selectmenu').one('click', function() {
    $('ul.ui-selectmenu-menu-dropdown:visible').jScrollPane({
        isScrollableH: false
    });
});
```

### CODE REVIEW

**Comment by jakob-stoeck** [comment]
Interestingly enough, the #308 link in the commit message references the wrong ticket: It’s from the main jquery-ui repo, not from this forked one.

**Comment by fnagel** [comment]
Would you mind posting a demo fiddle? See #61

**Comment by jakob-stoeck** [comment]
Sure: http://jsfiddle.net/GXtpC/1025/ So in short: selectmenu prevents other click bindings set on the menu, e.g. a custom scrollbar.

In the fiddle you see the same click handler bound to a normal div and to one inside of the selectmenu.

**Comment by fnagel** [comment]
Seems valid. Thanks for the contribution!

**Comment by ghost** [comment]
Just reverted my update from 1.5.0-pre to 1.4.0-pre. Scrolling is not working anymore.

**Comment by fnagel** [comment]
1.4.0 does not work, too?

**Comment by ghost** [comment]
doch, we use 1.4.0 (waiting for jQueryUI 1.11 so that selectmenu is part of jqui).
you can see it in the iframe here:
http://www.dat.de/online-services/service-fuer-verbraucher/gebrauchtfahrzeugwerte.html

**Comment by ghost** [comment]
maybe it has something to do with our own changes on that file?
we use jquery-migrate and we eliminated all "prop/attr", etc. warnings.
but maybe too much?!

**Comment by ghost** [comment]
ok, sorry for spamming....i tried again. it has nothing to do with jquery-migrate-warning-fixes.
details of the issue:
IE8 + selectmenu 1.5.0-pre
-->
Opening a Selectmenu and then clicking on the scroller (left-mouse-click) causes the selectmenu to get closed.

**Comment by jakob-stoeck** [comment]
@wuSam is right. My addition breaks clicking a _native_ scroll bar. Some quick workarounds which I tried had other downfalls. In the meantime my commit should be taken out again. Sorry for the inconvenience.

**Comment by ghost** [comment]
hmmm?! something happened yet?!

**Comment by fnagel** [comment]
Sorry for the delay, pretty busy atm.

I've reverted that patch in 32689789772a74b90f92b712d205745b1a2eb1d2

Any ideas how to fix both usecases?

**Pull request merged**
