### PR TITLE
Sequential typeahead should cycle through the options (same char)

### PR DESCRIPTION
**Pull request by limkianyong**
Fixes issue #144

### CODE REVIEW

**Comment by fnagel** [comment]
Wow! Many changes here. And you used the test unit! And I could auto merge this which is great. Thanks for that. 

Some questions: 
Did you test this in different browsers? 
Im a little concerned about the amount of code. You added about 140 lines which is quite a lot. Are there any possibilities to use less code? Another option would be to make an extension out of your contribution. I already thought about making the typeahead an "add-on".

Ive added some comments in the code, too.

I will take a look and test this asap and give you feedback. Perhaps I will have some questions about the test unit. I never used this for JS actually.

**Comment by fnagel** [comment]
Perhaps a look into the source of Jörn's Menu widget could help. His implementation seems to work great (Ive already tested this a few weeks ago) and is pretty compact: http://view.jqueryui.com/master/tests/visual/menu/menu.html

**Comment by limkianyong** [comment]
Hi fnagel, 

For the functions in _typeAhead, I left them there as to avoid polluting the selectmenu, since they would not be of much use outside the _typeAhead. 

I haven't profile the method yet, as I haven't met with any lag on my machine running the plugin, but of course, if they are too much of a performance hog, some post optimization can be done. :)

IMO, I think it should not be an add-on, as we are trying to replicate the actual functionality of the select menu and I use the typeahead and cycling whenever there's a large amount of items in the list.

As for the unit test, let me know if there's any issue. 

I haven't look at the Jörn's Menu widget - will look at his implementation tomorrow after work. :)

**Comment by limkianyong** [comment]
With regards to your previous questions: I have tested in IE6-9, Chrome 12, Safari 5.1, FF 4 and 5.

As for Jörn's Menu widget's code, it looks good, would have to do some refactoring to get there.

**Comment by fnagel** [comment]
I must confess Im not quite sure if its an performance issue to re-init the functions over and over again. Your testing sounds nice so far, did you test IE6 and IE7 in a virtual machine or standalone application?

 If we split your code into an extension its possible to use old style typeAhead and save some data, but youre right: type ahead should be a supported feature as its possible in native select.

What do you mean by "some refactoring"? Your code looks like much work spended but I do not feel comfortable adding 140 lines of code for typeAhead. 

You need to know we're planning to built a new Selectmenu widget from scratch. See issue #140

**Comment by limkianyong** [comment]
For IE6-8, I used IETester instead to save time firing up the VMs. 

For the lines of code, I must admit, it's possible to remove some of the functions and inline them, but would be done at the expense of readability. 

If the plan is to built the selectmenu from scratch, I would suggest we get more automated unit tests up to ease the rewriting. :)

**Comment by fnagel** [comment]
I will close this issue for now. Please reopen if there a news regarding this issue.

Please check out the new version of selectmenu we talked about: #140

**Comment by fnagel** [comment]
Would you mind take a look at this pull request? See #181

Should do the trick with less code. I did not test the code yet but it seems nice and I would love to get some third party feedback!

**Comment by limkianyong** [comment]
I have gone through the code and tested it on Chrome and FF for Mac.
It looks fine. :)

**Comment by fnagel** [comment]
Thanks for your fast feedback. I will test it myself asap and hopefully it will be included in v1.2

**Pull request closed without merging**
