### PR TITLE
Add the ability to put a css class

### PR DESCRIPTION
**Pull request by zalog**
I have a project where I need to style selectmenu in multiple ways http://ge.tt/4IY1mqh/v/0?c
I hope it helps

### CODE REVIEW

**Comment by fnagel** [comment]
Rejected. 

We had a feature like this before which have been removed. Please use widget method for this.

**Comment by zalog** [comment]
Sorry, can you give me an example?
This is how I use your plugin right now:
jQuery('SELECT').each(function(k){
    var el = jQuery(this);
    el.selectmenu({
        width: el.data('width'), // here I pass the width when I need it
        css: el.data('css') // here I pass the css class when I need it
    });
});

**Comment by fnagel** [comment]
Just use something like :

```
myElement.selectmenu("widget").addClass("myCssClass");
```

**Comment by zalog** [comment]
I see. This is my final code, how it looks?
http://jsfiddle.net/fVg8C/

**Comment by fnagel** [comment]
Looks good. Plese note there is a prepared jsFiddle, see #61 

And take a look at the upcoming official version of jQuery UI Selectmenu: #140

**Comment by zalog** [comment]
Thanks for your quick feedback :+1: 
I just noticed a problem on #293 after your commit. Let's move there

**Pull request closed without merging**
