### PR TITLE
Better image support (follow-up)

### PR DESCRIPTION
**Pull request by tauren**
@fnagel:

Thanks for the background image updates. I've just fixed the demo file default.html so that it works as well.

I'm really new to using github, and I've never done anything collaborative yet. So if I did this Pull Request wrong, I apologize. My intent is for you to pull my changes in default.html to your fork.

Tauren

### CODE REVIEW

**Comment by fnagel** [comment]
Did you recognize I added a background_image.html as a demo? 
http://github.com/fnagel/jquery-ui/blob/selectmenu/demos/selectmenu/background_image.html
I would prefer to show this functionality in a seperate file.

I've never done anything collaborative, too -- so dont panic :-) Did you send the Pull request by using Git or by using GitHub (aka web based action)?

**Comment by tauren** [comment]
Yes, I saw the new demo file. But I noticed the old one wasn't updated, so I fixed it. It would also be nice to link to the different demo pages from each other at some point so that it is easier for someone viewing live demos to see the other demos.

**Comment by tauren** [comment]
Oh yeah. I did the pull request using github's web interface. Not sure how to do it any other way.

**Comment by fnagel** [comment]
Sorry for the late response but I focused my free time to work on a TYPO3 extension. 

Afaics these changes are already in the latest commit: https://github.com/fnagel/jquery-ui/commit/8bf0ec22d9c2c477decb8b386b3bebc0957714dc

**Comment by tauren** [comment]
fnagel:

I'm referring to the changes I made to default.html:
https://github.com/tauren/jquery-ui/commit/8b966c34eb7c867384a1a544c5d901710b6932ab

**Comment by fnagel** [comment]
As I already mentioned: 
I would prefer to show the background image functionality in a seperate file, not in default.html

**Comment by tauren** [comment]
@fnagel: Oh, I see what you mean. However, there are still background image demos in default.html in your repo, so I fixed them. Those demos should be removed from default.html.

**Comment by fnagel** [comment]
I will do this with the next commit.

**Pull request closed without merging**
