### PR TITLE
Selectmenu fix for optgroups in popup

### PR DESCRIPTION
**Pull request by tauren**
Positioning of popups is totally broken when using selects that contain optgroups. I've fixed this issue, and you can pull it from tauren/jquery-ui.

The problem was that all LI heights were being including to determine the position, but when an optgroup was used, there are additional LIs for the optgroups that contain other LIs for the options. So this was causing the position get get whacked out because the optgroup LIs are very tall.

I changed the code to include the height of only the LIs representing options, not optgroups, above the selected LI. Then I add onto that the height of the optgroup label for the current group and any previous groups.  See the source in jquery.ui.selectmenu.js in the function _refreshPosition.

### CODE REVIEW

**Comment by fnagel** [comment]
I understand the problem in scroll demos, but Im not sure about these positioning problem. When does the widget isn in the viewport? Do I need to resize my browser to a specific size? MS IE? 
When applying your patch I see no difference using your demo file: https://github.com/tauren/jquery-ui/blob/selectmenu/demos/selectmenu/positioning.html

Do i understand you right that https://github.com/fnagel/jquery-ui/issues/#issue/26 (michaelcaplan first asked question) is not solved with this patch?

**Comment by tauren** [comment]
@fnagel: I'm afraid my multiple posts may have gotten confusing, sorry for that. I'll try to limit my comments to the specific issue at hand in each issue.

If you use positioning.html with selectmenu.js in your fnagel repo (not my patched version), you will see the problems. Basically, the first time you open the selectmenu, it is positioned properly. But if you scroll down and select different options, the select menu then repositions to the wrong location on the screen, and can even go off the screen. Note that this only seems to happen when optgroups are used. See further explanation in #26. The problems are fixed in my repo (tauren/jquery-ui). 

I'm using Chrome on Mac OS and Linux, but I'm pretty sure the problem would exist in all browsers. This is because when using optgroups, the height of LI tags for an optgroup is really big. The logic doesn't differentiate between LI's that are for options vs optgroups.

I do not think my solution solves michaelcaplan's problem as posted in #26. I was experiencing positioning problems with long select menus and mistakenly thought my problem was the same as his, which is why I posted to #26. Once I figured out the problem is related to optgroups, I fixed it and added comments to #26 which was probably not the best place for them.

**Comment by fnagel** [comment]
I aware of the bug now, but your patch for _refreshPosition does not work for me. Within my latest tests I found out that the position plugin will fix this issue. Please be patient.

**Comment by tauren** [comment]
What do you mean it doesn't work for you? If you checkout my repo and go to the positioning.html page, something doesn't work? What doesn't work? It's working perfectly for me.

Of course, I do think that using the position plugin is ultimately the right way to go. I hope that you'll include a test for popups that contain optgroups and have enough content that scrolling is required.

Thanks for your efforts on all of this! Let me know if there is something I can do.

**Comment by fnagel** [comment]
Please check out the latest commit. I've implemented the jQuery UI position plugin.This problem should be fixed as I now use offset.top to get the correct offset to the newElement. Any feedback is appreciated.

**Pull request closed without merging**
