### PR TITLE
Support for changing icons by _setOption #2

### PR DESCRIPTION
**Pull request by demonslord**
1st Change: 
- Support for jQuery UI 1.8.x
  - Tested with jQuery UI 1.8.23 + jQuery 1.8.2

2nd Change: 
- Support for changing icons by _setOption.
  - Tested with jQuery UI 1.8.23 + jQuery 1.8.2

e.g:

```
$("#MySelectmenu").selectmenu("option","icons",[
 {
  icon: "ui-icon-alert",
  find: ".MySelectmenu_Item_0"
 }])
```

Best Regards,
Alexander Bulei

### CODE REVIEW

**Comment by fnagel** [comment]
That one looks nice. I will take a look asap!

Thanks for your contribution!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by demonslord** [comment]
Hi  fnagel, which issue?

**Comment by fnagel** [comment]
Ahem, this issue, this pull request?

**Comment by demonslord** [comment]
:+1: works for me in modern/updated browsers ;)

**Comment by fnagel** [comment]
Thats sounds great but I wont pull this as long as its addressing multiple
issues.

**Comment by demonslord** [comment]
hey fnagel, will make 1 PR per issue.

Do you wonna jquery 1.8.x legancy?

Best Regards.

**Comment by fnagel** [comment]
Hey Alexander, thanks for updating! Im currently very busy (got a knew job
lately), so please be patient.
Based upon the latest commit would be perfect!

**Comment by demonslord** [comment]
Will close with PR.

Reason: Invalid.
Valid PR: #291

**Pull request closed without merging**
