### PR TITLE
Selectmenu minMenuWidth option

### PR DESCRIPTION
**Pull request by tauren**
I've implemented a minMenuWidth option in my selectmenu branch and am hoping you'll pull it into your branch.This commit contains the changes:
https://github.com/tauren/jquery-ui/commit/c1addbc6ad2874302308d43daf4c1ff5726de7aa

Basically, if the width of the menu list is less than minMenuWidth, it is set to minMenuWidth:

```
o.minMenuWidth && this.list.width() < o.minMenuWidth && this.list.width(o.minMenuWidth);
```

It really only makes sense to use this option if you are not specifying menuWidth and letting the menu width be determined automatically.

In my opinion, selectmenu looks best when the menu is allowed to be the default width. So I prefer to never set menuWidth. However, when I use liquid layouts and element widths are based on percentages, the width of menus with lots of options may be too narrow to fully display the option names, especially when the menu has a scrollbar.

This option allows the menus to retain the default width for most situations, but prevents the menu from being narrower than minMenuWidth.

### CODE REVIEW

**Comment by fnagel** [comment]
Thanks for your contribution.

I'm not quite sure when to use this, can you provide a demo? It's only a small change without bloating the code so I'm willing to do this soon!

**Comment by tauren** [comment]
@fnagel: I just added a demo of using minMenuWidth. I only tested in Google Chrome on OSX. Hopefully this will show you why this option would be nice to have.

Also, the very last section on this demo page illustrates a bug in selectmenu. When a select has a width: 100% within a sized container, the menu popup is sized way too large and disappears off the left side of the screen.  I do not have a fix for this yet. My workaround is to set the width of the selectmenu to the width of the select:

```
$('select').each(function() {
    var $this = $(this);
    $this.selectmenu({
        style:'popup',
        width: $this.hasClass("nosize") ? undefined : $this.width(),
        minMenuWidth: $this.hasClass("withmin") ? 100 : undefined
    });
});
```

**Comment by fnagel** [comment]
Please open a new issue for the second bug.

I will test your demo asap.

**Comment by fnagel** [comment]
Im sorry to inform you that this feature wont be included. As there is a new version of this plugin (see #140) which will hopefully be included in jQuery UI 1.9. Its built from scratch and most of my time will be used maintaining the official version.

This branch will be maintained but with focus on bugfixes.

**Comment by fnagel** [comment]
Please reopen if you need this feature too.

**Pull request closed without merging**
