### PR TITLE
Cleaning up indent and white space

### PR DESCRIPTION
**Pull request by thg2k**
Hi fnagel, i'm sending you a couple of commits to clean up white spaces of the selectmenu plugin in selectmenu branch.
Let me know if it works for you.

### CODE REVIEW

**Comment by fnagel** [comment]
Thanks for your contribution, nice code formatting is always appreciated :-) Especially when releasing the first tagged version tomorrow.

You seem to be much more familiar with Git than I am. Is there a way to remove the forked jQuery UI branches expect for master and my own selectmenu branch? People use the wrong branches all the time and ask me where the selectmenu files are all the time. 
The (original fork) tags within the download dialog (here on GitHub) cause similar problems too but I need them to see which stable version Im merging to my fork. Any ideas?

**Comment by thg2k** [comment]
Hi fnagel, i read a couple of books about git and still i have huuge problems with it. sometimes it drives me crazy, but i think i can help on this one.
You just want to delete a branch from yours github repository right? it's a totally separate repository from the one on your computer, so deleting it locally won't help.. you have to do this:
git push origin :master
following the git push syntax: git push <remote> <localbranch>:<remotebranch>
if you omit the local branch it's like push null to the remote branch..i.e. delete it.
don't blame me, i also think it's kind of freak. :)

**Comment by thg2k** [comment]
oh it seems my "html tags" got lost in my previous comment.. the general syntax for push is:
git push REMOTE LOCALBRANCH:REMOTEBRANCH
this should help you understand what's happening..at least i found this explanation useful when i read it!

**Comment by fnagel** [comment]
With your code above I would delete the master branch in GitHub, right?
Should I delete the unneeded local branches, too?

**Comment by fnagel** [comment]
Figured out how to. Thanks again for your help!

**Comment by thg2k** [comment]
hey sorry i didn't follow up.. to answer your question yes, i would delete all the branches..it's only confusing i think.. what's the point of having a "master" branch? do you keep it updated with the upstream? you should start considering a port to 1.9 APIs of your great selectmenu..that of course would fit in a branch by itself.

**Comment by fnagel** [comment]
np, Im pretty busy, too :-)

Mhh Im using TortoiseGit (a GUI, Im not a console kid at all) and Im not able to delete the local branches as they are remote. 
Yes, Im syncing the master branch with jquer-ui and merge this with my own selectmenu branch from time to time (mostly to new UI versions).
I planned to upgrade to 1.9 when its released. Propably with the 1.2 release of selectmenu. There are already a few issues what needs to be done to make it work with jQuery UI 1.9.x.

**Pull request merged**
