### PR TITLE
Updated the select event so it has a chance to cancel selection by return

### PR DESCRIPTION
**Pull request by bluefox**
Updated the select event so it has a chance to cancel selection by returning false.

### CODE REVIEW

**Comment by fnagel** [comment]
I will take a look as soon v1.2 is released. Please be patient.

**Comment by fnagel** [comment]
Sorry for the late response. Would you mind to update your branch and describe a usecase so I can update the wiki?

**Comment by fnagel** [comment]
Is this related to #208?

**Comment by bluefox** [comment]
Yeah #208 would be an use case for this patch, though he seems to want to have an additional event like beforeSelect, my patch is allowing select to cancel the selection.

**Comment by fnagel** [comment]
Closed as outdated.

**Pull request closed without merging**
