### PR TITLE
Adding the ability for the format option to use 'this' where 'this' is th

### PR DESCRIPTION
**Pull request by geedew**
Adding the ability for the format option to use 'this' where 'this' is the current option you are formatting.

Previously, the only thing that you had acces to was the 'text' that is in the option. Allowing you to format that text is great, however, what if your formatting requires meta information that only the option can provide (IE. attribute <option data-type="mine" .. /> ).
With this change, you are able to use 'this' within the format function, where this is the current option you are formatting. $(this).data('type') //mine

### CODE REVIEW

**Comment by fnagel** [comment]
I will take a look as soon as v1.2 is released. Thanks for your contribution!

**Comment by fnagel** [comment]
So this enhances the format function by adding additional infos to the provided function, correct?
Seems like a nice feature

This pull request has some additional changes in it but I would need only one fix per pull reuest. Please open a new pull request based upon my latest commit. If you like I could patch my files without a new pull request as its a small change afaics.

ps: Do you notice the new, built from scratch version of selectmenu? It has advanced templating features, so take a look: #140

**Comment by geedew** [comment]
yeah, actually, I went and rebuilt the entire thing so that it has full
multiple=multiple support, so this request is probably out of date at this
point.

**Comment by geedew** [comment]
In fact, I will update my branch, and add in the qunit test cases I have,
as my code is working pretty well (still using the widget factory)... I
keep up to date on the new selectmenu.

and yes, mine is currently working and supporting full multiple=multiple,
I'll update it today

**Comment by fnagel** [comment]
There is a feature requets for that #71

**Comment by fnagel** [comment]
Are you able to provide a working branch built upon my latest commit? Any news on this issue?

I actually closed the feature request for multiple support as the new version of selectmenu (see #140) will not support multiple, but hey, if theres a working modification it would be a great feature! Please give feedback.

**Comment by geedew** [comment]
This is pretty old at this point; trash it and I will see about adding a mulitple into the newer 1.9 release candidate

**Comment by fnagel** [comment]
Any help is appriciated! Take a look at the wiki page and use the comment functionality.

http://wiki.jqueryui.com/w/page/12138056/Selectmenu

**Pull request closed without merging**
