### PR TITLE
fixed : javascript error when destroying elements if no label was bind to

### PR DESCRIPTION
**Pull request by nicooprat**
fixed : javascript error when destroying elements if no label was bind to the element

just testing if this label exists before trying to change its attribute or unbind events

### CODE REVIEW

**Comment by nicooprat** [comment]
The error was :
"$("label[for=" + this.newelement.attr("id") + "]").attr("for", this.element.attr("id")) is undefined"

**Comment by fnagel** [comment]
Thanks for your contribution. 

Im not able to reproduce the issue in FF6. Afaik the selector should remain empty and do not fire the chained methods.
In which browser am I able to reproduce the issue?

**Comment by nicooprat** [comment]
I'm working on FF6 (Mac OS X 10.7).

I had this error when applying selectmenu in a Colorbox (ajax loaded content) then closing this colorbox.

Hope it helps..!

**Comment by fnagel** [comment]
Are you able to provide a demo fiddle? See #61

**Comment by nicooprat** [comment]
I could but it would take a lot of time to integrate colorbox and all its stuff... what's more, this error message is only shown in the console, so we won't see it in jsFiddle..! :/

**Comment by betalb** [comment]
This bug is only reproducible with jQuery 1.6

It seems that starting from 1.6, jQuery will return `undefined` from method attr if attribute doesn't exist
So in this case `attr` works as getter and will return `undefined` or `String`

http://jsfiddle.net/KwvKg/

**Comment by nicooprat** [comment]
Ok, thanks betalb... better than me ;)

**Comment by fnagel** [comment]
Thanks for your help!

I will fix this soon. Take a look here #118

**Comment by fnagel** [comment]
This should be fixed in latest commit. Please test and give feedback!

**Comment by nicooprat** [comment]
Many thanks !

**Pull request closed without merging**
