### PR TITLE
Fix to issue #147, removes jumping and flickering occurring when selectmenu is opened 

### PR DESCRIPTION
**Pull request by Ninkasi**
TESTED with IE9 (9.0.8112.16421), Chrome (13.0.782.112 m) AND FF (5.0.1) 
Libraries used: 
jquery-1.5.1
jquery.ui.1.8.9
jquery.ui.position.js
jquery.ui.selectmenu.js (2011.08.10)

### CODE REVIEW

**Comment by yaheys** [comment]
Hi Ninkasi,

I have found a small bug in your code, when you re-click the main anchor the menu div is not closing. I think I have solve it. Just change the _toogle body to the following:

```
_toggle: function(event, retainFocus) {
    if ( this.listWrap.is('.' + this.widgetBaseClass + '-open') ) {
        this.close(event, retainFocus);
    } else {
        this.open(event);
    }
},
```

Thanks for your fix.

Yanko

**Comment by fnagel** [comment]
I would need some informations to classify your comment:
In which browsers did you test this? 

@Ninkasi & @yaheys
I assume you still experience the #147 issue. Can you give me a step by step tutorial how to reproduce the issue? I was not able to find any problems atm. 
Perhaps you can provide a demo fiddle? See #61

**Comment by Ninkasi** [comment]
Browsers i was using were:
IE9 (9.0.8112.16421
Chrome (13.0.782.112 m)
FF (5.0.1)

I was able to get rid of the jumping with this patch i posted but it only seems to fix this issue for the "dropdown" style menu.

**Comment by fnagel** [comment]
As i commented within the code I would need step by step tutorial how to reproduce the issue or a test file / fiddle to reproduce the issue. 

Problem does only occur in IE9 and latest stable Chrome, correct?

**Comment by yaheys** [comment]
Hi,

Browsers where I detected were IE7 and IE8. The fix from Ninkasi solve my
issue (the dropdown lost focus in the first click), but introduce the bug of
no closing de dropdown menu when you click in the main anchor when it is
open. I sent the code to him so it won't occur.

Yanko (@yaheys)

2011/8/20 fnagel <
reply@reply.github.com>

**Comment by fnagel** [comment]
@yaheys
The problem is that Ninkasi code breaks the popup style. He is working on a new version.
Im still not able to reproduce the issue. Please post a demo fiddle and describe more accurate.

**Comment by fnagel** [comment]
Please give feedback. Release 0.1.2 is already delayed.

**Comment by Ninkasi** [comment]
You can find my latest patch here: https://github.com/Ninkasi/jquery-ui/blob/selectmenu/ui/jquery.ui.selectmenu.js

**Comment by fnagel** [comment]
Sorry for the late response. I was pretty busy and my left spare time was used to create the new version of Selectmenu widget (see #140).

I was not able to reproduce the issue by using the posted demo ( http://www.students.oamk.fi/~jsaarija/selectmenu-test/ ). Ive tested in FF7, IE9 and latest stable Chrome.
What extactly needs to be done to reproduce the issue? Please with OS, Browser and a step-by-step tutorial.

**Comment by fnagel** [comment]
I feel cautiously optimistic Ive found a solution for this whole flickering/jumping/positioning issue. Finally. See and comment #147

**Comment by fnagel** [comment]
Please test latest commit and give some feedback at #147

**Comment by fnagel** [comment]
Please test version 1.2 or latest dev / commit and give feedback!

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by fnagel** [comment]
Please give some feedback!

**Comment by Ninkasi** [comment]
Sorry for late response. Just got 1.2 version installed and tested. After bit of testing seems that it works like a charm. Thank you very much for your efforts!

**Comment by fnagel** [comment]
Thanks for your feedback!

**Pull request closed without merging**
